### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by KFlash** [escaya/escaya#11]
- [ ] Write tons of error recovery tests

- [ ] Write tons of tests for loc tracking in 'normal mode'

- [ ] Optimize and tweak the parser in normal mode

- [ ] Fix non-failing early errors

- [ ] Finish recovery mode

- [ ] Finish incremental parsing code

As of now EScaya can parse everything, and it recover and reconstruct AST from everything included human language ( see tests).

The non-failing early error tests can't be finished yet because of the way we mark nodes as 'dirty' for incremental parsing. Early error nodes isn't an syntax errors and should only be bypassed, but for that need to write tons of recovery tests to make sure this actually happen.

The parser is 70% complete, and the incremental parsing code will be published in the end. Still need tweaking and optimizing, but it works. It is shipped with the NPM package of EScaya so it can be tried out there.

**Comment by KFlash** [comment]
The few non-failing early error cases left is related to keywords in strict mode. Little tricky because a 'keyword' in recovery mode can be start of an statement, and we need to "fall through" and continue to parse.

**Comment by KFlash** [comment]
Early errors - done! Can be tested in the online demo. Going to fix the missing loc tests and do some cleanup before pushing and close this issue

**Comment by KFlash** [comment]
Need to finish the Escaya-fuzzer and all the tools before finishing this issue ticket. It's needed to see how escaya behave in "real life" scenarios and as part of different tools.

**Comment by KFlash** [comment]
This is still WIP! I'm now in the processing where I go through all details regarding the AST and make sure it's optimized for 3rd party tools like code generators, walkers and so on. The AST is also tweaked so it will become smaller than before.

**Comment by KFlash** [comment]
The process of finalizing the EScaya parser have started...

**Comment by KFlash** [comment]
I got busy in RL as of now, but I will get back to Escaya in the future. There are many improvements I'm going to add to this code, and it will be more or less like what you can see [here](https://escaya.github.io/escaya/kataw_ast/).

It's part of my private code, but the AST is similar to Escaya AST, and so is the error recovery mode.

**Comment by KFlash** [comment]
The plan is to change the Escaya AST into what you can see [here](https://github.com/kataw/kataw).

@aladdin-add Click on the link above and look at the readme. That's the plans I have now to improve EScaya. Also click on the two demo links at the bottom of the readme.

Do you think it's possible to "port this" to Escaya?
